Work in progress on deploy script

diff --git a/tasks/travis_deploy b/tasks/travis_deploy
--- a/tasks/travis_deploy
+++ b/tasks/travis_deploy
@@ -18,6 +18,58 @@ function headHash() {
   local gitHash=`git rev-parse --short HEAD`
   eval $__hash="'$gitHash'"
 }
+function revertChanges() {
+  echo "Resetting branch after error to $1"
+  git reset --hard $1
+}
+function revertChangesAndExit() {
+  revertChanges $1
+  exit 1
+}
+function processStage() {
+  # First read version number from the master branch.
+  master
+  version elementVersion || {
+    echo "Error to read element version number."
+    exit 1
+  }
+  headHash masterHash || {
+    echo "Error to read maste's HEAD hash."
+    exit 1
+  }
+  stage
+  headHash stageHash || {
+    echo "Can't read stage's HEAD hash :("
+    exit 1;
+  }
+  ./node_modules/.bin/arc bump $elementVersion || revertChangesAndExit stageHash
+  ./node_modules/.bin/arc docs || revertChangesAndExit stageHash
+  ./node_modules/.bin/arc changelog || revertChangesAndExit stageHash
+  git add -A
+  git commit -m "[CI] Automated commit after stage build (bump, docs, changelog)." || revertChangesAndExit stageHash
+
+  echo "Stage updated, merging with master"
+  master
+  git merge --no-ff -m "[CI] Automated merge stage->master" stage || {
+    echo "Unable to merge changes to master."
+    stage
+    revertChangesAndExit stageHash
+  }
+  git add -A
+  git commit -m "[CI] Automated commit after merge stage->master"
+  git push origin master || {
+    echo "Unable to push changes to master."
+    revertChanges masterHash
+    stage
+    revertChangesAndExit stageHash
+  }
+  stage
+  git push origin stage || {
+    echo "Changes to master has been made, however error occurred when pushing changes to the stage. Please, merge stage manually from master."
+    exit 1;
+  }
+}
+
 
 if [[ "${TRAVIS_PULL_REQUEST}" == "false" ]] && [[ "${TRAVIS_BRANCH}" == "stage" ]]; then
   echo "Updating stage branch and marging with master..."
@@ -32,14 +84,3 @@ if [[ "${TRAVIS_PULL_REQUEST}" == "false" ]] && [[ "${TRAVIS_BRANCH}" == "master
   echo "Deploying release to master branch..."
   exit
 fi
-
-master
-version elementVersion
-headHash masterHash
-stage
-
-echo ""
-echo "Element version"
-echo $elementVersion
-echo "hash: "
-echo $masterHash
